# Generated by Django 3.2.5 on 2021-07-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha_two_code', models.CharField(default='', max_length=10)),
                ('country', models.CharField(default='', max_length=200)),
                ('domain', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=100)),
                ('web_page', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
